language: rust
cache:
  cargo: true
rust:
- nightly
- stable
os: osx
osx_image:
- xcode12.2 # macOS 10.15.7
- xcode11.3 # macOS 10.14.6
- xcode10.1 # macOS 10.13
before_install:
  - rustup component add clippy rustfmt
script:
  - cargo build
  - cargo test --verbose -- --nocapture
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
